### ISSUE TITLE
[17th Aug] Delete slides from dropbox

### ISSUE THREAD

**Issue by adamralph** [Particular/Course.Slides#3]
[According to @mauroservienti](https://particularsoftware.slack.com/archives/developer-education/p1483698547000247) the slides are also sitting in DropBox somewhere.

Let's delete that copy to prevent it becoming it's own branch.

/cc @Particular/training-maintainers

**Comment by SamCamhi** [comment]
@adamralph what slides?

**Comment by adamralph** [comment]
@SamCamhi the slides contained in this repo. They're both in PDF and PowerPoint format in the repo root: https://github.com/Particular/Course.Slides

**Comment by seanfarmar** [comment]
@adamralph just to make sure, these are the NserviceBus course slides (not the ADSD)

**Comment by SamCamhi** [comment]
Below is the content of Dropbox/Nservicebus.course.  @andreasohlund is the owner of the dropbox.  Please do not delete the slides in the ADSD folder.  @udidahan uses them to give his class.

![image](https://cloud.githubusercontent.com/assets/2587871/21722828/f6cff8ca-d436-11e6-99f7-b4409a13ffcf.png)

**Comment by weralabaj** [comment]
Also those slides are linked in the ADSD alumni forum, so if you delete them from Dropbox, please let me or Dennis know.

**Comment by adamralph** [comment]
@weralabaj is that link publicly accessible?

**Comment by adamralph** [comment]
@weralabaj ignore. I got mixed up between these slides and the ADSD slides.

**Comment by adamralph** [comment]
@weralabaj can you change the link to point to this repo instead? You can do that now.

**Comment by adamralph** [comment]
Does anyone know what else all the content is in that dropbox folder? It seems we have quite a few things floating around in dropbox in various places. It would be really good to get this all into GitHub instead.

**Comment by weralabaj** [comment]
> @weralabaj can you change the link to point to this repo instead? You can do that now.

I guess, but then won't everybody need access to this repo? Do we want it to be publicly accessible?

**Comment by adamralph** [comment]
@weralabaj this repo is public.

**Comment by weralabaj** [comment]
So that won't work for ADSD slides ;) I think Dropbox is good enough for now at least.

**Comment by adamralph** [comment]
A DropBox search yields the following results, from 2012:

![image](https://user-images.githubusercontent.com/677704/43640864-730b09ce-9719-11e8-8f6b-347cc24db76b.png)

@Particular/engineers any objection to deleting those files from DropBox?

**Comment by andreasohlund** [comment]
Go for it

**Comment by adamralph** [comment]
Done. I left the "...Student.docx" file because I couldn't find it anywhere else.
